var bodyParser = require('body-parser');
var jsonParser = bodyParser.json();
var cors = require('cors');

//routes definition
const adress = require('app/routes/adress.routes');
const contact = require('app/routes/contact.routes.js');
const country = require('app/routes/country.routes.js');
const destination = require('app/routes/destination.routes.js');
const geolocation = require('app/routes/geolocation.routes.js');
const routesIndex = require('app/routes/index.router.js');
const hotelChain = require('app/routes/HotelChain.routes.js');
const EstablishmentType = require('app/routes/EstabServiceCategory.routes');
const Formule = require('app/routes/Formule.routes');
const EstablishmentService = require('app/routes/EstablishmentService.routes');
const EstablishmentServiceCateg = require('app/routes/EstabServiceCategory.routes');
const estabType = require('app/routes/EstablishmentType.routes.js');
const meta = require('app/routes/MetaInfo.routes.js');
const etablishment = require('app/routes/Establishment.routes.js');
const restruction = require('app/routes/Restruction.routes');
const description = require('app/routes/description.routes');
const language = require('app/routes/language.routes');
const product = require('app/routes/product.routes');
const productfacility = require('app/routes/productfacility.routes');
const productfacilityType = require('app/routes/productFacilityType.routes');
const hebergementType = require('app/routes/HebergementType.router');
const roomType = require('app/routes/roomType.router');
const currency = require('app/routes/currency.routes');
const payementcard = require('app/routes/payementcard.routes');
const users = require('app/routes/client.router');
const auth = require('app/routes/auth.router');
const adminAgency = require('app/routes/adminAgency.router');
const agentAgency = require('app/routes/agentAgency.router');
const clientapi = require('app/routes/clientAPI.router');
const superadmin = require('app/routes/superAdmin.router');
const occupancy = require('app/routes/RoomOccupancy.routes');
const estabCondition = require('app/routes/estabCondition.routes');
const estabCancellation = require('app/routes/estabCancellation.routes');
const ratetype = require('app/routes/ratetype.routes.js');
const ratepromotion = require('app/routes/promotion.router.js');
const ratepromotiontype = require('app/routes/promotype.router.js');
const concillationPolicy = require('app/routes/concellationPolicy.routes');
const rateDiscount = require('app/routes/rateDiscount.router.js');
const ratemarge = require ('app/routes/ratemarge.router.js');
const agencyDeposit = require ('app/routes/AgencyDeposit.routes');
const rateSupplement = require('app/routes/rateSupplement.router.js');
const rate = require('app/routes/rate.routes.js');
// routes
module.exports = function (app) {
    app.use('/api', routesIndex);
    app.use('/api/auth', jsonParser, cors(), auth);
    app.use('/api/users', jsonParser, cors(), users);
    app.use('/api/admin', jsonParser, cors(), adminAgency);
    app.use('/api/agent', jsonParser, cors(), agentAgency);
    app.use('/api/clientapi', jsonParser, cors(), clientapi);
    app.use('/api/superadmin', jsonParser, cors(), superadmin);
    app.use('/api/adress', jsonParser, cors(), adress);
    app.use('/api/contact', jsonParser, cors(), contact);
    app.use('/api/country', jsonParser, cors(), country);
    app.use('/api/destination', jsonParser, cors(), destination);
    app.use('/api/geolocation', jsonParser, cors(), geolocation);
    app.use('/api/hotelChain', jsonParser, cors(), hotelChain);
    app.use('/api/estabType', jsonParser, cors(), estabType);
    app.use('/api/meta', jsonParser, cors(), meta);
    app.use('/api/establishment', jsonParser, cors(), etablishment);
    app.use('/api/restruction', jsonParser, cors(), restruction);
    app.use('/api/description', jsonParser, cors(), description);
    app.use('/api/language', jsonParser, cors(), language);
    app.use('/api/product', jsonParser, cors(), product);
    app.use('/api/establishmentType', jsonParser, cors(), estabType);
    app.use('/api/formules', jsonParser, cors(), Formule);
    app.use('', jsonParser, cors(), EstablishmentService);
    app.use('/api/productFacility', jsonParser, cors(), productfacility);
    app.use('/api/productFacilityTypes', jsonParser, cors(), productfacilityType);
    app.use('/api/HebergementType', jsonParser, cors(), hebergementType);
    app.use('/api/RoomType', jsonParser, cors(), roomType);
    app.use('/api/currency', jsonParser, cors(), currency);
    app.use('', jsonParser, payementcard);
    app.use('/api/estabCateg', jsonParser, cors(), EstablishmentServiceCateg);
    app.use('/api/estabService', jsonParser, cors(), EstablishmentService);
    app.use('/api/paymentMethod', jsonParser, cors(), payementcard);
    app.use('/api/occupancy', jsonParser, cors(), occupancy);
    app.use('/api/condition', jsonParser, cors(), estabCondition);
    app.use('/api/estabCancellation', jsonParser, cors(), estabCancellation);
    app.use('/api/ratetype', jsonParser, cors(), ratetype);
    app.use('/api/ratepromotion', jsonParser, cors(), ratepromotion);
    app.use('/api/ratepromotiontype', jsonParser, cors(), ratepromotiontype);
    app.use('/api/concillation', jsonParser, cors(), concillationPolicy);
    app.use('/api/reduction' , jsonParser, cors(), rateDiscount);
    app.use('/api/supplement' , jsonParser, cors(), rateSupplement);
    app.use('/api/ratemarge' , jsonParser, cors(), ratemarge);
    app.use('/api/agencyDeposit' , jsonParser, cors(), agencyDeposit);
    app.use('/api/rate', jsonParser, cors(), rate);
};
